package by.andruhovich.subscription.command;

public enum CommandType {
    //user
    LOGIN, SIGN_IN, BLOCK_USER, UNBLOCK_USER, UPDATE_USER, SHOW_USERS, FIND_USER_BY_LOGIN, FIND_USER_BY_ACCOUNT_NUMBER,
    FIND_USER_BY_SUBSCRIPTION_ID, FIND_USER_BY_PAYMENT_NUMBER,

    //publication
    SHOW_PUBLICATIONS, ADD_PUBLICATION, DELETE_PUBLICATION, UPDATE_PUBLICATION, FIND_PUBLICATION_BY_NAME,
    FIND_PUBLICATION_BY_AUTHOR
}
