package by.andruhovich.subscription.command;

public enum CommandType {
    //account
    FIND_ACCOUNT_BY_USER_ID, RECHARGE, TAKE_LOAN,

    //user
    LOGIN, LOGOUT, SIGN_UP, BLOCK_USER, UNBLOCK_USER, EDIT_USER, SHOW_USERS, FIND_USER_BY_LOGIN, FIND_USER_BY_ACCOUNT_NUMBER,
    FIND_USER_BY_SUBSCRIPTION_ID, FIND_USER_BY_PAYMENT_NUMBER, FIND_BLOCKED_USERS_BY_ADMIN_ID,

    //publication
    SHOW_PUBLICATIONS, ADD_PUBLICATION, DELETE_PUBLICATION, EDIT_PUBLICATION, FIND_PUBLICATION_BY_NAME,
    FIND_PUBLICATIONS_BY_AUTHOR, FIND_PUBLICATIONS_BY_GENRE, FIND_PUBLICATIONS_BY_PUBLICATION_TYPE, PARSE_PUBLICATION,

    //author
    SHOW_AUTHORS, ADD_AUTHOR, DELETE_AUTHOR, EDIT_AUTHOR, PARSE_AUTHOR,

    //genre
    SHOW_GENRES, ADD_GENRE, DELETE_GENRE, EDIT_GENRE, PARSE_GENRE,

    //publication_type
    SHOW_PUBLICATION_TYPES, ADD_PUBLICATION_TYPE, DELETE_PUBLICATION_TYPE, EDIT_PUBLICATION_TYPE, PARSE_PUBLICATION_TYPE,

    //subscription
    SHOW_SUBSCRIPTIONS, ADD_SUBSCRIPTION, ACTIVATE_SUBSCRIPTION, DEACTIVATE_SUBSCRIPTION,
}
